"""empty message

Revision ID: 289d7fde476f
Revises: 7f79281c36e6
Create Date: 2021-01-29 20:18:36.383002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289d7fde476f'
down_revision = '7f79281c36e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('all_day', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'all_day')
    # ### end Alembic commands ###
