"""empty message

Revision ID: 4881baecb71b
Revises: 289d7fde476f
Create Date: 2021-01-29 20:19:32.844555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4881baecb71b'
down_revision = '289d7fde476f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('habitat_id', sa.String(length=80), nullable=True))
    op.add_column('calendar', sa.Column('pets', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'pets')
    op.drop_column('calendar', 'habitat_id')
    # ### end Alembic commands ###
