"""empty message

Revision ID: 4a9d7ee9b505
Revises: 5af7fedff1cb
Create Date: 2021-02-22 18:03:03.443156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9d7ee9b505'
down_revision = '5af7fedff1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_picture', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_picture')
    # ### end Alembic commands ###
