"""empty message

Revision ID: 51811c5509ff
Revises: 08425ca8f506
Create Date: 2021-01-28 16:53:51.078499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51811c5509ff'
down_revision = '08425ca8f506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('all_day', table_name='calendar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('all_day', 'calendar', ['all_day'], unique=True)
    # ### end Alembic commands ###
