"""empty message

Revision ID: 7f79281c36e6
Revises: 51811c5509ff
Create Date: 2021-01-29 20:04:42.148349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f79281c36e6'
down_revision = '51811c5509ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'pets')
    op.drop_column('calendar', 'all_day')
    op.drop_column('calendar', 'habitat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('habitat_id', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('calendar', sa.Column('all_day', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('calendar', sa.Column('pets', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
