"""empty message

Revision ID: b7291686593c
Revises: c422da1342ae
Create Date: 2021-01-26 15:33:33.085393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7291686593c'
down_revision = 'c422da1342ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pet_type', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.String(length=100), nullable=True),
    sa.Column('habitat_id', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
